console.log("merhabadünya");
console.log("sddsfdslf");
6 + 8;
console.log(6 + 8);
console.warn("hata hata");
const sayı = 3;
let dil = 6;
dil = 8;
console.log(dil);
// ***********const
console.log(typeof dil);
const sa = "hello";
const se = "mergabs";
console.log(sa + se);
console.log(sa + "  " + se);
let dils = "javasrip";
dils = "html";
const dilso = "html";
pes = "merhaba pes";
console.log(pes);
var pes = "hello kale";
console.warn();
