var sayı = 5;
console.log(`benim sayım ${sayı}`);
const name = "ahmet";
const birtOfDay = 1978;
console.log(`${name}in yaşı ${2022 - birtOfDay}`);
const pi = 3.14;
// const r = Number(prompt("please enter r "));
// console.log(r);
// const alan = pi * r ** 2;
// console.log(`spuare of circle ${alan}`);
// console.log(`square of circle ${Math.floor(alan)}`);
// console.log(`square of circle ${Math.ceil(alan)}`);
// console.log(`square of circle ${Math.trunc(alan)}`);
// console.log(`square of circle ${Math.round(alan)}`);
// // prompt(alan);
const randumNumber = Math.random();
// console.log(randumNumber * 100);
console.log((randumNumber * 100).toFixed(0));
console.log(Math.ceil(randumNumber * 100));
let a = 5;
a++;
console.log(a++);
y = a + 8;
console.log(y == 15);
console.log({ y });
const number = 321;
c = number % 10;
s = number / 10;
console.log(c);
k = Math.trunc(s % 10);
console.log(k);
t = Math.trunc(number / 100);
console.log(t);
console.log(5 === "5");
console.log(5 == "5");
console.log(5 !== "5");
console.log(5 < "3");
